### ISSUE TITLE
Duplicated Reborn/Nightfall-Breakthrough functions

### ISSUE THREAD

**Issue by eduzappa18** [mohabhassan/NightFall#17]
This is not really an issue but just something to have in mind if there is ever a client version of Reborn/Nightfall for Breakthrough  
Or for old mods/maps that make use of this functions

The trigonometric functions `atan`, `cos`, `sin` and `tan` are different than the ones in the vanilla game
Reborn functions expects radians, while Breakthrough functions expects degrees
So the same imput gives different results

The scripting documentation for Breakthrough, should have a warning about this

---

This are the scripts that use some of this functions in Breakthrough

```yml
# global/parachuteDrop.scr
line 116:    local.swayY = local.d*(sin local.angle)
line 119:    local.dZ = local.d*(cos local.angle)

# maps/e1l4/SunkShip.scr
line  93:    local.t1 = sin (local.t*180)

# maps/e2l3/FinalHouse.scr
line 543:    local.xup = atan local.towards[0] local.towards[2]
line 562:    local.zup = atan local.towards[1] local.towards[2]
```

Other duplicated functions like *sqrt* or *netname* works the same or don't cause any conflict with old scripts
